# Generated by Django 4.1.1 on 2022-12-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_files_options_alter_folder_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
